# Generated by Django 2.0 on 2024-03-10 11:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie_list', '0004_allmovies'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='allmovies',
            table='allmovies',
        ),
    ]
