# Generated by Django 2.0 on 2024-03-11 14:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie_list', '0006_topmovies'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BoxOffice',
        ),
    ]
