version: '3'

services:
  django-app:
    image: django-app  # Django 应用镜像名称，需要在此之前构建好
    ports:
      - "8000:8000"
#    networks:
#      - mynetwork

  react-app:
    image: react-app  # React 应用镜像名称，需要在此之前构建好
    ports:
      - "3000:3000"
    depends_on:
      - django-app
#    networks:
#      - mynetwork
#networks:
#  mynetwork:
#    driver: bridge

# docker-compose up

